image: ruby:2.1

stages:
  - syntax
  - build
  - trigger

build:
  stage: build
  script:
    - rake build
  # disable artefact upload until it's fixed
  # see https://leap.se/code/issues/8221
  #artifacts:
  #  paths:
  #    - pkg/leap_cli-1.9.gem

# trigger leap_platform pipeline
trigger:
  stage: trigger
  type: deploy
  script:
    - curl -s -X POST -F token=${PLATFORM_TRIGGER_TOKEN} -F ref=develop https://0xacab.org/api/v3/projects/129/trigger/builds
