image: ruby:2.1

stages:
  - syntax
  - build
  - trigger

build:
  stage: build
  script:
    - rake build
    - rake install
  artifacts:
    paths:
      - pkg/leap_cli-*.gem
    name: "leap_cli_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
    expire_in: 3 month

# trigger leap_platform pipeline
trigger:
  stage: trigger
  type: deploy
  script:
    - curl -s -X POST -F token=${PLATFORM_TRIGGER_TOKEN} -F ref=develop https://0xacab.org/api/v3/projects/129/trigger/builds
