image: leapcode/ruby:2.1-slim

stages:
  - build
  - test
  - trigger

build:
  stage: build
  script:
    - "rake build"
    - "gem install --user-install pkg/leap_cli-*.gem"
    - export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
    - leap
  artifacts:
    paths:
      - pkg/leap_cli-*.gem
    name: "leap_cli_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
    expire_in: 3 month

test:
  stage: test
  script:
    - "gem install --user-install pkg/leap_cli-*.gem"
    - export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
    - leap
    - "rake test"

# trigger leap_platform pipeline
trigger:
  stage: trigger
  type: deploy
  script:
    - "curl -s -X POST -F token=${PLATFORM_TRIGGER_TOKEN} -F ref=develop https://0xacab.org/api/v3/projects/129/trigger/builds"
